engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ecmaFeatures:
  modules: true
  jsx: true
env:
  es6: true
  node: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- __tests__/
